### ISSUE TITLE
Dalamud updating issue 

### ISSUE THREAD

**Issue by seivan** [marzent/XIV-on-Mac#100]
According to [status](https://status.xivmac.com/status/xivmac) it has `Is Dalamud Available?` as down. 
Is this an actual web service related to updating Dalamud? 

Enabling Dalamud and launching, will fail updating Dalamud, so I was wondering if that's related. 
Is there a way to update Dalamud or check Dalamud updates available without actually launching the game? 

What url can I look at to monitor for updates?

**Comment by FleetAdmiralButter** [comment]
Hi,

The "Is Dalamud Available?" check indicates whether Dalamud is available for the currently shipping game patch. Since 6.3 dropped yesterday, they're still working on getting it updated for this version of the game.

Once Dalamud is available for 6.3, that indicator on status.xivmac.com will flip to green and Dalamud should update the next time you log in with XIV on Mac.

The web backend that serves Dalamud updates are called "Kamori". Those are running fine (but don't have a Dalamud update as yet).

**Comment by marzent** [comment]
This is also not a XOM issue

**Comment by seivan** [comment]
@marzent

> This is also not a XOM issue

Well, yes and no. 

The message popping up says 

>  "An error occured downloading and installing Dalamud. Please check your network connection and make sure Dalamud is compatible with the current game version.";

I understand it's not a XOM issue directly, but XOM says the update failed and I should check internet connection instead of saying there is no update available. Can it instead distinguish between "no update" available, instead of "failed" which gives the impression it tried and it failed based on some unknown setting. 


How would a user know if it's compatible?
Where would a user look to see if it's compatible? 

Suggestion is to either add a URL for further debugging, e.g the repo/site for Dalamud to check their issue tracker/FAQ. 
Or distinguish between update missing and update failing. Since there's many things that can go wrong with an installation as opposed to missing is a single occurrence failure point.
