### ISSUE TITLE
Game locks Steam library despite not using Steam license

### ISSUE THREAD

**Issue by silasary** [marzent/XIV-on-Mac#165]
This is a bit of a weird one.

* I have a normal non-steam Windows License.  This is what I have selected in the XIV on Mac settings.
* I have Steam Family Sharing set up with someone who owns the steam version of the game.
* I launch XIV on Mac while Steam is running
* FFXIV bubbles up to the top of my recently played on steam, and they are locked out of the game because steam thinks I'm using their copy.

My current workaround is to quit steam whenever I launch the game.  I can immediately reopen it afterwards, but ideally the launcher doesn't call the steam functions at all if you're not using a steam license.

**Comment by seathasky** [comment]
What's happening is XOM is picking up the Steam license through Steam Family as you suspected, there is no way for us to **NOT** do this is the only way for us to allow Mac users to use their FF14 Steam Windows license. We (XOM launcher) probes Steam every time you launch the game through our launch. This happens regardless if you have a steam license or not. If it detects one, it will use it. **This is intentional.** 

Your best bet is to close Steam when playing FF14 to avoid this issue or continue to use Whiskey/Wineserver/CX if you have to have Steam open.

Unless @marzent decides to make a work around for this, he'll either respond or you're stuck closing Steam/Using other options. Best of luck!
