### ISSUE TITLE
Can't launch ACT anymore

### ISSUE THREAD

**Issue by Velin92** [marzent/XIV-on-Mac#82]
Hello ACT doesn't launch anymore.

It's not like it crashes or closes by saying that is not updated.
It simply does not launch at all.

I tried also reinstalling, and it's saying that Microsoft .NET Frameowkr 4.6 or above are missing, I tried to install the latest framework of the XIV On Mac tools, but nothing changed.

**Comment by marzent** [comment]
There haven’t been any changes related to ACT the past few months with XOM so I assume it is not an actual issue with the app. 
In order to install .NET Framework you need to install all of them in order (lowest to highest). 
Having said that ACT support will probably be dropped in the next release due to technical reasons, now would be a good time to migrate over to IINACT
